# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_todo', '0003_auto_20160215_1504'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
