# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_todo', '0005_auto_20160217_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='collaborators',
        ),
        migrations.AddField(
            model_name='task',
            name='collaborator1',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='collaborator2',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='collaborator3',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
